"""Rename servers table to aws_servers

Revision ID: 5fea8e09462c
Revises: d3e478354daf
Create Date: 2025-06-02 23:51:34.888180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fea8e09462c'
down_revision = 'd3e478354daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('instance_id'))

    op.drop_table('servers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('instance_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('instance_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('availability_zone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('launch_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('instance_id'), ['instance_id'], unique=True)

    # ### end Alembic commands ###
