"""Add AWS fields to Server model

Revision ID: d3e478354daf
Revises: 
Create Date: 2025-06-01 08:47:48.642292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e478354daf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instance_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instance_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('availability_zone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('launch_time', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['instance_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('launch_time')
        batch_op.drop_column('state')
        batch_op.drop_column('availability_zone')
        batch_op.drop_column('instance_type')
        batch_op.drop_column('instance_id')

    # ### end Alembic commands ###
